### ISSUE TITLE
SDK 1.6.0 requires external library

### ISSUE THREAD

**Issue by ilker-aktuna** [Insta360Develop/CameraSDK-Android#73]
I have been using 1.5.0 on my apps. To support new camera X4, I changed to the SDK 1.6.0 and now the app crash because it requires external libraries.
changed to:
```
    implementation 'com.arashivision.sdk:sdkcamera:1.6.0'
    implementation 'com.arashivision.sdk:sdkmedia:1.6.0'

```

crash log:
```

2024-06-07 22:56:27.745 24562-24562 AndroidRuntime          com....test  E  FATAL EXCEPTION: main
                                                                                                    Process: com.aktuna.gear.watchcontrolforinsta360, PID: 24562
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libinsbase.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at com.arashivision.insbase.NativeLibsLoader.load(NativeLibsLoader.java:15)
                                                                                                    	at com.arashivision.insbase.sys.SysInfo.<clinit>(SysInfo.java:21)
                                                                                                    	at com.arashivision.insbase.sys.SysInfo.init(SysInfo.java:25)
                                                                                                    	at com.arashivision.insbase.InsBase.init(InsBase.java:19)
                                                                                                    	at com.arashivision.sdkmedia.InstaMediaSDK.init(Unknown Source:0)
                                                                                                    	at com.aktuna.test.MyApp.onCreate(MyApp.java:20)
```

I can't find the libinsbase.so in the SDK package.
It is available in the example apk but I am not sure how to use it.
Can you please provide guidance ?

**Comment by ilker-aktuna** [comment]
why doesn't anybody answer ?

**Comment by ilker-aktuna** [comment]
I see now that the libraries are added for 64bit but not 32bit
Ok but how do we force the phone to use 64bit ?
